baseURL: https://melvinquick.github.io/
languageCode: en-us
title: Melvin Quick
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Melvin Quick
  description: "This is a place for me to store my thoughts, links to my social medias, my CV, etc."
  keywords: [Blog, Portfolio, PaperMod]
  author: Melvin Quick
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Melvin Quick
    subtitle: "Fueled by coffee, code, and iron"
    imageUrl: "/images/me.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: me
    # buttons: # uncomment this section to get buttons on the home page
    #   - name: Posts
    #     url: posts
    #   - name: About
    #     url: posts/about

  socialIcons: # comment this out to remove the social icons from the home page
    - name: reddit
      url: "https://www.reddit.com/user/WittyWampus/"
    - name: github
      url: "https://github.com/melvinquick"
    - name: linkedin
      url: "https://www.linkedin.com/in/melvinquick/"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    - identifier: social_media_links
      name: Socials
      url: /posts/socials/
      weight: 50
    - identifier: about_me
      name: About
      url: /posts/about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
